name: heroi_da_vez
description: Heroi da Vez - Aplicação de causas sociais
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: 4.4.1
  provider: ^6.0.3
  objectbox_flutter_libs: any
  objectbox: ^1.6.2
  url_launcher: ^6.1.5
  shared_preferences: ^2.0.15
  json_annotation: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.0.0
  json_serializable: ^6.3.1
  objectbox_generator: any

flutter:
  uses-material-design: true
  assets:
    - assets/
